skip debian packages
There is an issue with mosquitto and libwebsockets:

ERROR: Nothing PROVIDES 'libuv' (but /mnt/ram/builds/a9bbdc1a/1/mirrors/venus/sources/meta-victronenergy/meta-alternatives/recipes-connectivity/libwebsockets/libwebsockets_3.0.0.bb DEPENDS on or otherwise requires it). Close matches:
  libxv
  libva
  libgudev
NOTE: Runtime target 'mosquitto' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['mosquitto', 'libwebsockets', 'libuv']
NOTE: Runtime target 'dbus-mqtt-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dbus-mqtt-dev', 'mosquitto', 'libwebsockets', 'libuv']
NOTE: Runtime target 'dbus-mqtt' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['dbus-mqtt', 'mosquitto', 'libwebsockets', 'libuv']
ERROR: Required build target 'packagegroup-venus-debian' has no buildable providers.
Missing or unbuildable dependency chain was: ['packagegroup-venus-debian', 'dbus-mqtt', 'mosquitto', 'libwebsockets', 'libuv']