git-fetch-remote: fix error setting upstream branch
fetching upstream first fixes this error:
--------------- sources/bitbake - https://github.com/victronenergy/bitbake.git -------------
Cloning into 'sources/bitbake'...
remote: Counting objects: 39010, done.
remote: Total 39010 (delta 0), reused 0 (delta 0), pack-reused 39010
Receiving objects: 100% (39010/39010), 19.09 MiB | 12.70 MiB/s, done.
Resolving deltas: 100% (25061/25061), done.
Checking connectivity... done.
Branch 1.28 set up to track remote branch 1.28 from origin.
Switched to a new branch '1.28'
fatal: Couldn't find remote ref upstream/1.28
Unexpected end of command stream
error: the requested upstream branch 'upstream/1.28' does not exist
hint:
hint: If you are planning on basing your work on an upstream
hint: branch that already exists at the remote, you may need to
hint: run "git fetch" to retrieve it.
hint:
hint: If you are planning to push out a new local branch that
hint: will track its remote counterpart, you may want to use
hint: "git push -u" to set the upstream config as you push.